name: CI
on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
      continue-on-error: true
    - run: npm install -w=common/validators 
    - run: npm run build -w=common/validators 
    - run: npm run test -w=common/validators 
    - run: npm run build -w=common/model
    - run: npm run test -w=common/model
    - run: npm install
      continue-on-error: true
    - run: npm run build -w=common/dal
    - run: npm run build -w=common/bll
    - run: npm run build -w=common/openApiClient
    - run: npm --prefix=apps/openApiServer install
    - run: npm --prefix=apps/openApiServer run build
    - run: npm --prefix=apps/community install
    - run: npm --prefix=apps/community run build